import React, { useEffect, useState } from 'react';

import { Card, FormField, Loader } from '../components';

const RenderCards = ( {data, title }) => {
    if(data?.length > 0){
        return data.map((post) => <Card key = {post._id} {...post} />)
    }
return(
    <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>{title}</h2>
)
}
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

const [searchText, setSearchText] = useState('');
  
  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#222328]'> The Community Showcase</h1>
            <p className= " mt-2 text-[#666e75] text-[14px]">Browse through of a collection of imagination and visually stunning images generated by DALL -E AL</p>
        </div>
        <div className='mt-16'>
            <FormField />
        </div>
        <div className='mt-10'>
        { loading ? (
            <div>
                <Loader />
                </div>
        ):(
            <>
            { searchText &&(
                <h2 className='font-medium text-[#666e75]'> showing results for <span className='text-[#222328]'>{searchText}</span></h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs: grid-cols-2 grid-cols-1 gap-3'>
                {searchText ?(
                    <RenderCards 
                    data= {[]}
                    title = "no search results found"
                    />):(
                    <RenderCards
                        data={[]}
                        title="no posts found"/>
                )}
            </div>
        </>
        )
        }
    </div>
    </section>
   
  )
}

export default Home